name: Test Binaries
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "v*"
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test_binaries_unix:
    name: Test Binaries (Linux & macOS)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: linux-amd64
          os: ubuntu-latest
        - suffix: linux-arm64
          os: ubuntu-24.04-arm
        - suffix: linux-musl-amd64
          os: ubuntu-latest
        - suffix: linux-musl-arm64
          os: ubuntu-24.04-arm
        - suffix: darwin-amd64
          os: macos-15-intel
        - suffix: darwin-arm64
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Artifact Archive
      uses: actions/download-artifact@v7
      with:
        name: todo-highlight-lsp-${{ matrix.suffix }}.tar.gz
        path: release-dist

    - name: Checksums
      run: |
        ls -lha release-dist
        for file in release-dist/**;
          do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256";
        done

    - name: Extract Artifact Archive
      run: |
        tar -xzvf release-dist/todo-highlight-lsp-${{ matrix.suffix }}.tar.gz -C .

    - name: Test Bin
      run: ./todo-highlight-lsp --version
  test_binaries_windows:
    name: Test Binaries (Windows)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: windows-amd64
          os: windows-latest
        - suffix: windows-arm64
          os: windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Artifact Archive
      uses: actions/download-artifact@v7
      with:
        name: todo-highlight-lsp-${{ matrix.suffix }}.zip
        path: release-dist

    - name: Checksums
      shell: pwsh
      run: |
        # Iterate over all files in release-dist and compute SHA256
        Get-ChildItem -Recurse release-dist | ForEach-Object {
          $file = $_.FullName
          if (-not $_.PSIsContainer) {
            $hash = Get-FileHash $file -Algorithm SHA256
            $hash.Hash | Out-File -FilePath "$file.sha256" -Encoding ascii
          }
        }

    - name: Extract Artifact Archive
      shell: pwsh
      run: |
        $zipPath = "release-dist\todo-highlight-lsp-${{ matrix.suffix }}.zip"
        Expand-Archive -Path $zipPath -DestinationPath "." -Force

    - name: Test Bin
      shell: pwsh
      run: |
        ./todo-highlight-lsp.exe --version
